
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "C:/vcpkg/scripts/buildsystems/vcpkg.cmake:309 (find_program)"
      - "C:/Program Files/CMake/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:146 (include)"
      - "CMakeLists.txt:3 (project)"
    mode: "program"
    variable: "Z_VCPKG_CL"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "cl"
    candidate_directories:
      - "C:/Users/X/.codex/tmp/arg0/codex-arg00xgXgo/"
      - "F:/mingw64/bin/"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/"
      - "F:/cursor/cursor/resources/app/bin/"
      - "D:/vmware/bin/"
      - "C:/Python313/Scripts/"
      - "C:/Python313/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/"
      - "C:/Program Files (x86)/Incredibuild/"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "C:/ProgramData/chocolatey/bin/"
      - "C:/Users/X/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/X/.dotnet/tools/"
      - "C:/Program Files/MySQL/MySQL Server 8.0/bin/"
      - "C:/Users/X/.lmstudio/bin/"
      - "C:/Users/X/AppData/Roaming/npm/"
      - "F:/PyCharm/PyCharm 20/"
      - "C:/Program Files/Docker/Docker/resources/bin/"
      - "G:/project/shuati-Cli/build/Release/"
      - "C:/Program Files/nodejs/"
      - "C:/Users/X/.local/bin/"
      - "C:/Program Files/CMake/bin/"
      - "F:/phpstudy_pro/Extensions/MySQL8.0.12/bin/"
      - "C:/Program Files/Git/cmd/"
      - "G:/project/shuati-Cli/node_modules/.bin/"
      - "C:/Users/X/AppData/Local/pnpm/"
      - "C:/Users/X/.trae/tools/trae-gopls/current/"
      - "C:/Users/X/.trae/sdks/workspaces/1a4c88ac/versions/node/current/"
      - "C:/Users/X/.trae/sdks/versions/node/current/"
      - "G:/project/shuati CLI/build/Release/"
      - "C:/Users/X/.cargo/bin/"
      - "F:/PyCharm/PyCharm 2025.1.1.1/bin/"
      - "F:/intell IJ/IntelliJ IDEA 2025.1.1.1/bin/"
      - "F:/Clion/CLion 2025.1.1/bin/"
      - "F:/Android_SDk/platform-tools/"
      - "F:/Android_SDk/build-tools/"
      - "F:/Microsoft VS Code/bin/"
      - "C:/Users/X/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.0.1-full_build/bin/"
      - "F:/Antigravity/bin/"
      - "F:/Kiro/bin/"
      - "F:/Windsurf/bin/"
      - "C:/Users/X/AppData/Local/shuati-cli/"
      - "C:/Users/X/AppData/Local/Programs/shuati-cli/"
      - "C:/Users/X/Documents/"
      - "D:/OpenClaw_Workspace/node_modules/.bin/"
      - "C:/Users/X/AppData/Local/OpenAI/Codex/bin/"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.409.1734.0_x64__2p2nqsd0c76g0/app/resources/"
    searched_directories:
      - "C:/Users/X/.codex/tmp/arg0/codex-arg00xgXgo/cl.com"
      - "C:/Users/X/.codex/tmp/arg0/codex-arg00xgXgo/cl.exe"
      - "C:/Users/X/.codex/tmp/arg0/codex-arg00xgXgo/cl"
      - "F:/mingw64/bin/cl.com"
      - "F:/mingw64/bin/cl.exe"
      - "F:/mingw64/bin/cl"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/cl.com"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/cl.exe"
      - "C:/Program Files/Eclipse Adoptium/jdk-21.0.8.9-hotspot/bin/cl"
      - "F:/cursor/cursor/resources/app/bin/cl.com"
      - "F:/cursor/cursor/resources/app/bin/cl.exe"
      - "F:/cursor/cursor/resources/app/bin/cl"
      - "D:/vmware/bin/cl.com"
      - "D:/vmware/bin/cl.exe"
      - "D:/vmware/bin/cl"
      - "C:/Python313/Scripts/cl.com"
      - "C:/Python313/Scripts/cl.exe"
      - "C:/Python313/Scripts/cl"
      - "C:/Python313/cl.com"
      - "C:/Python313/cl.exe"
      - "C:/Python313/cl"
      - "C:/Windows/System32/cl.com"
      - "C:/Windows/System32/cl.exe"
      - "C:/Windows/System32/cl"
      - "C:/Windows/cl.com"
      - "C:/Windows/cl.exe"
      - "C:/Windows/cl"
      - "C:/Windows/System32/wbem/cl.com"
      - "C:/Windows/System32/wbem/cl.exe"
      - "C:/Windows/System32/wbem/cl"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/cl"
      - "C:/Windows/System32/OpenSSH/cl.com"
      - "C:/Windows/System32/OpenSSH/cl.exe"
      - "C:/Windows/System32/OpenSSH/cl"
      - "C:/Program Files/dotnet/cl.com"
      - "C:/Program Files/dotnet/cl.exe"
      - "C:/Program Files/dotnet/cl"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/cl.com"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/cl.exe"
      - "C:/Program Files/Microsoft SQL Server/150/Tools/Binn/cl"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl.com"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl.exe"
      - "C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/cl"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/cl.com"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/cl.exe"
      - "C:/Program Files/NVIDIA Corporation/NVIDIA App/NvDLISR/cl"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/cl.com"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/cl.exe"
      - "C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common/cl"
      - "C:/Program Files (x86)/Incredibuild/cl.com"
      - "C:/Program Files (x86)/Incredibuild/cl.exe"
      - "C:/Program Files (x86)/Incredibuild/cl"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl.com"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl.exe"
      - "C:/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/cl"
      - "C:/ProgramData/chocolatey/bin/cl.com"
      - "C:/ProgramData/chocolatey/bin/cl.exe"
      - "C:/ProgramData/chocolatey/bin/cl"
      - "C:/Users/X/AppData/Local/Microsoft/WindowsApps/cl.com"
      - "C:/Users/X/AppData/Local/Microsoft/WindowsApps/cl.exe"
      - "C:/Users/X/AppData/Local/Microsoft/WindowsApps/cl"
      - "C:/Users/X/.dotnet/tools/cl.com"
      - "C:/Users/X/.dotnet/tools/cl.exe"
      - "C:/Users/X/.dotnet/tools/cl"
      - "C:/Program Files/MySQL/MySQL Server 8.0/bin/cl.com"
      - "C:/Program Files/MySQL/MySQL Server 8.0/bin/cl.exe"
      - "C:/Program Files/MySQL/MySQL Server 8.0/bin/cl"
      - "C:/Users/X/.lmstudio/bin/cl.com"
      - "C:/Users/X/.lmstudio/bin/cl.exe"
      - "C:/Users/X/.lmstudio/bin/cl"
      - "C:/Users/X/AppData/Roaming/npm/cl.com"
      - "C:/Users/X/AppData/Roaming/npm/cl.exe"
      - "C:/Users/X/AppData/Roaming/npm/cl"
      - "F:/PyCharm/PyCharm 20/cl.com"
      - "F:/PyCharm/PyCharm 20/cl.exe"
      - "F:/PyCharm/PyCharm 20/cl"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.com"
      - "C:/Program Files/Docker/Docker/resources/bin/cl.exe"
      - "C:/Program Files/Docker/Docker/resources/bin/cl"
      - "G:/project/shuati-Cli/build/Release/cl.com"
      - "G:/project/shuati-Cli/build/Release/cl.exe"
      - "G:/project/shuati-Cli/build/Release/cl"
      - "C:/Program Files/nodejs/cl.com"
      - "C:/Program Files/nodejs/cl.exe"
      - "C:/Program Files/nodejs/cl"
      - "C:/Users/X/.local/bin/cl.com"
      - "C:/Users/X/.local/bin/cl.exe"
      - "C:/Users/X/.local/bin/cl"
      - "C:/Program Files/CMake/bin/cl.com"
      - "C:/Program Files/CMake/bin/cl.exe"
      - "C:/Program Files/CMake/bin/cl"
      - "F:/phpstudy_pro/Extensions/MySQL8.0.12/bin/cl.com"
      - "F:/phpstudy_pro/Extensions/MySQL8.0.12/bin/cl.exe"
      - "F:/phpstudy_pro/Extensions/MySQL8.0.12/bin/cl"
      - "C:/Program Files/Git/cmd/cl.com"
      - "C:/Program Files/Git/cmd/cl.exe"
      - "C:/Program Files/Git/cmd/cl"
      - "G:/project/shuati-Cli/node_modules/.bin/cl.com"
      - "G:/project/shuati-Cli/node_modules/.bin/cl.exe"
      - "G:/project/shuati-Cli/node_modules/.bin/cl"
      - "C:/Users/X/AppData/Local/pnpm/cl.com"
      - "C:/Users/X/AppData/Local/pnpm/cl.exe"
      - "C:/Users/X/AppData/Local/pnpm/cl"
      - "C:/Users/X/.trae/tools/trae-gopls/current/cl.com"
      - "C:/Users/X/.trae/tools/trae-gopls/current/cl.exe"
      - "C:/Users/X/.trae/tools/trae-gopls/current/cl"
      - "C:/Users/X/.trae/sdks/workspaces/1a4c88ac/versions/node/current/cl.com"
      - "C:/Users/X/.trae/sdks/workspaces/1a4c88ac/versions/node/current/cl.exe"
      - "C:/Users/X/.trae/sdks/workspaces/1a4c88ac/versions/node/current/cl"
      - "C:/Users/X/.trae/sdks/versions/node/current/cl.com"
      - "C:/Users/X/.trae/sdks/versions/node/current/cl.exe"
      - "C:/Users/X/.trae/sdks/versions/node/current/cl"
      - "G:/project/shuati CLI/build/Release/cl.com"
      - "G:/project/shuati CLI/build/Release/cl.exe"
      - "G:/project/shuati CLI/build/Release/cl"
      - "C:/Users/X/.cargo/bin/cl.com"
      - "C:/Users/X/.cargo/bin/cl.exe"
      - "C:/Users/X/.cargo/bin/cl"
      - "F:/PyCharm/PyCharm 2025.1.1.1/bin/cl.com"
      - "F:/PyCharm/PyCharm 2025.1.1.1/bin/cl.exe"
      - "F:/PyCharm/PyCharm 2025.1.1.1/bin/cl"
      - "F:/intell IJ/IntelliJ IDEA 2025.1.1.1/bin/cl.com"
      - "F:/intell IJ/IntelliJ IDEA 2025.1.1.1/bin/cl.exe"
      - "F:/intell IJ/IntelliJ IDEA 2025.1.1.1/bin/cl"
      - "F:/Clion/CLion 2025.1.1/bin/cl.com"
      - "F:/Clion/CLion 2025.1.1/bin/cl.exe"
      - "F:/Clion/CLion 2025.1.1/bin/cl"
      - "F:/Android_SDk/platform-tools/cl.com"
      - "F:/Android_SDk/platform-tools/cl.exe"
      - "F:/Android_SDk/platform-tools/cl"
      - "F:/Android_SDk/build-tools/cl.com"
      - "F:/Android_SDk/build-tools/cl.exe"
      - "F:/Android_SDk/build-tools/cl"
      - "F:/Microsoft VS Code/bin/cl.com"
      - "F:/Microsoft VS Code/bin/cl.exe"
      - "F:/Microsoft VS Code/bin/cl"
      - "C:/Users/X/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.0.1-full_build/bin/cl.com"
      - "C:/Users/X/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.0.1-full_build/bin/cl.exe"
      - "C:/Users/X/AppData/Local/Microsoft/WinGet/Packages/Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-8.0.1-full_build/bin/cl"
      - "F:/Antigravity/bin/cl.com"
      - "F:/Antigravity/bin/cl.exe"
      - "F:/Antigravity/bin/cl"
      - "F:/Kiro/bin/cl.com"
      - "F:/Kiro/bin/cl.exe"
      - "F:/Kiro/bin/cl"
      - "F:/Windsurf/bin/cl.com"
      - "F:/Windsurf/bin/cl.exe"
      - "F:/Windsurf/bin/cl"
      - "C:/Users/X/AppData/Local/shuati-cli/cl.com"
      - "C:/Users/X/AppData/Local/shuati-cli/cl.exe"
      - "C:/Users/X/AppData/Local/shuati-cli/cl"
      - "C:/Users/X/AppData/Local/Programs/shuati-cli/cl.com"
      - "C:/Users/X/AppData/Local/Programs/shuati-cli/cl.exe"
      - "C:/Users/X/AppData/Local/Programs/shuati-cli/cl"
      - "C:/Users/X/Documents/cl.com"
      - "C:/Users/X/Documents/cl.exe"
      - "C:/Users/X/Documents/cl"
      - "D:/OpenClaw_Workspace/node_modules/.bin/cl.com"
      - "D:/OpenClaw_Workspace/node_modules/.bin/cl.exe"
      - "D:/OpenClaw_Workspace/node_modules/.bin/cl"
      - "C:/Users/X/AppData/Local/OpenAI/Codex/bin/cl.com"
      - "C:/Users/X/AppData/Local/OpenAI/Codex/bin/cl.exe"
      - "C:/Users/X/AppData/Local/OpenAI/Codex/bin/cl"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.409.1734.0_x64__2p2nqsd0c76g0/app/resources/cl.com"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.409.1734.0_x64__2p2nqsd0c76g0/app/resources/cl.exe"
      - "C:/Program Files/WindowsApps/OpenAI.Codex_26.409.1734.0_x64__2p2nqsd0c76g0/app/resources/cl"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\X\\.codex\\tmp\\arg0\\codex-arg00xgXgo"
        - "F:\\mingw64\\bin"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.8.9-hotspot\\bin"
        - "f:\\cursor\\cursor\\resources\\app\\bin"
        - "D:\\vmware\\bin\\"
        - "C:\\Python313\\Scripts\\"
        - "C:\\Python313\\"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Windows\\system32"
        - "C:\\Windows"
        - "C:\\Windows\\System32\\Wbem"
        - "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\Windows\\System32\\OpenSSH\\"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.8.9-hotspot\\\\bin"
        - "C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\"
        - "C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\"
        - "C:\\Program Files\\NVIDIA Corporation\\NVIDIA App\\NvDLISR"
        - "C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common"
        - "C:\\Program Files (x86)\\Incredibuild"
        - "C:\\Program Files (x86)\\Windows Kits\\10\\Windows Performance Toolkit\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "C:\\Users\\X\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\X\\.dotnet\\tools"
        - "F:\\cursor\\cursor\\resources\\app\\bin"
        - "C:\\Program Files\\MySQL\\MySQL Server 8.0\\bin"
        - "C:\\Users\\X\\.lmstudio\\bin"
        - "C:\\Users\\X\\.dotnet\\tools"
        - "C:\\Users\\X\\AppData\\Roaming\\npm"
        - "F:\\PyCharm\\PyCharm 20"
        - "C:\\Program Files\\Docker\\Docker\\resources\\bin"
        - "G:\\project\\shuati-Cli\\build\\Release"
        - "C:\\Program Files\\nodejs\\"
        - "C:\\Users\\X\\.local\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Program Files\\CMake\\bin"
        - "F:\\phpstudy_pro\\Extensions\\MySQL8.0.12\\bin"
        - "C:\\Program Files\\Git\\cmd"
        - "./node_modules/.bin"
        - "C:\\Users\\X\\AppData\\Local\\pnpm"
        - "c:\\\\Users\\\\X\\\\.trae\\\\tools\\\\trae-gopls\\\\current"
        - "c:\\\\Users\\\\X\\\\.trae\\\\sdks\\\\workspaces\\\\1a4c88ac\\\\versions\\\\node\\\\current"
        - "c:\\\\Users\\\\X\\\\.trae\\\\sdks\\\\versions\\\\node\\\\current"
        - "c:\\Users\\X\\.trae\\tools\\trae-gopls\\current"
        - "c:\\Users\\X\\.trae\\sdks\\workspaces\\1a4c88ac\\versions\\node\\current"
        - "c:\\Users\\X\\.trae\\sdks\\versions\\node\\current"
        - "G:\\project\\shuati CLI\\build\\Release"
        - "C:\\Users\\X\\.cargo\\bin"
        - "F:\\PyCharm\\PyCharm 2025.1.1.1\\bin"
        - "F:\\intell IJ\\IntelliJ IDEA 2025.1.1.1\\bin"
        - "F:\\Clion\\CLion 2025.1.1\\bin"
        - "F:\\Android_SDk\\platform-tools"
        - "F:\\Android_SDk\\build-tools"
        - "F:\\Microsoft VS Code\\bin"
        - "C:\\Users\\X\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe\\ffmpeg-8.0.1-full_build\\bin"
        - "F:\\Antigravity\\bin"
        - "F:\\Kiro\\bin"
        - "F:\\Windsurf\\bin"
        - "C:\\Users\\X\\AppData\\Local\\shuati-cli"
        - "C:\\Users\\X\\AppData\\Local\\Programs\\shuati-cli"
        - "C:\\Users\\X\\Documents"
        - "D:\\OpenClaw_Workspace\\node_modules\\.bin"
        - "C:\\Users\\X\\AppData\\Local\\OpenAI\\Codex\\bin"
        - "C:\\Program Files\\WindowsApps\\OpenAI.Codex_26.409.1734.0_x64__2p2nqsd0c76g0\\app\\resources"
...
